name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7]
        example:
          - "examples/freedom-e-sdk_freertos-blinky"
          - "examples/freedom-e-sdk_freertos-blinky-system-view"
          - "examples/freedom-e-sdk_freertos-pmp-blinky"
          - "examples/freedom-e-sdk_hello"
          - "examples/freedom-e-sdk_multicore-hello"
          - "examples/freedom-e-sdk_sifive-welcome"
          - "examples/freedom-e-sdk_spi"
          - "examples/freedom-e-sdk_test-coreip"
          - "examples/freedom-e-sdk_timer-interrupt"
          - "examples/freedom-e-sdk_user-mode"
          - "examples/freedom-e-sdk_user-syscall"
          - "examples/native-blink_asm"
          - "examples/zephyr-blink"
          - "examples/zephyr-hello-world"
          - "examples/zephyr-synchronization"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          platformio run -d ${{ matrix.example }}
